name: brianji.github.io
description: My personal website.
publish_to: 'none' 
version: 1.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^4.0.5755
  url_launcher: ^6.0.3

flutter:
  uses-material-design: true

  assets:
    - images/me.jpg