name: brianji_github_io
description: My personal website.
publish_to: 'none' 
version: 1.2.0

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^5.0.6295
  url_launcher: ^6.0.12

flutter:
  uses-material-design: true

  assets:
    - images/me.jpg
